backend/models/Message.php
<?php

namespace backend\models;

use Yii;
use yii\helpers\ArrayHelper;
use common\models\ValueHelpers;
/**
 * This is the model class for table "message".
 *
 * @property integer $id
 * @property string $language
 * @property string $translation
 *
 * @property SourceMessage $id0
 */
class Message extends SourceMessage
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'message';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id', 'language'], 'required'],
            [['id'], 'integer'],
            [['translation'], 'string'],
            [['language'], 'string', 'max' => 16]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'language' => 'Language',
            'translation' => 'Translation',
            'category' => 'Category',

        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getId0()
    {
        return $this->hasOne(SourceMessage::className(), ['id' => 'id']);
    }


    /**
     * get all messages
     * @return array
     */
    public function getMessageList()
    {
        $arg=$this->find()->from('source_message')
            ->innerJoin('message','source_message.id=message.id')
            ->asArray()->all();
        return ValueHelpers::changeValuess(ArrayHelper::map($arg,'id','message'));
    }

    /**
     * get language list
     * @return array
     */
    public function getLanguageList()
    {
        $dropoptions=Message::find()->asArray()->all();
        $arr=ArrayHelper::map($dropoptions,'language','id');
        return ValueHelpers::changeKeys($arr);
    }

    /**
     * get language list
     * @return array
     */
    public function getTranslationList()
    {
        $dropoptions=Message::find()->asArray()->all();
        $arr=ArrayHelper::map($dropoptions,'translation','id');
        return ValueHelpers::changeKeys($arr);
    }

    /**
     * get categories
     * @return array
     */
    public function getCategoryList()
    {
        $arg=$this->find()->from('source_message')
            ->innerJoin('message','source_message.id=message.id')
            ->asArray()->all();
        return ValueHelpers::changeValuess(ArrayHelper::map($arg,'id','category'));
    }

    public function getCategoryTitle()
    {
        $arg=$this->find()->from('source_message')
            ->innerJoin('message','source_message.id=message.id')
            ->asArray()->all();
        return ArrayHelper::map($arg,'id','category');
    }
    /**
     * get categories
     * @return array
     */
    public function getMessageTitle()
    {
        $arg=$this->find()->from('source_message')
            ->innerJoin('message','source_message.id=message.id')
            ->asArray()->all();
        return ArrayHelper::map($arg,'id','message');
    }
}

backend/controllers/MessageController.php
<?php

namespace backend\controllers;

use Yii;
use backend\models\Message;
use backend\models\MessageSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use common\components\languageSwitcher;
use yii\filters\AccessControl;
use common\models\PermissionHelpers;

/**
 * MessageController implements the CRUD actions for Message model.
 */
class MessageController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['index','view','update','delete'],
                        'allow' => true,
                        'roles' => ['@'],
                        'matchCallback' => function ($rule, $action) {

                            return PermissionHelpers::requireMinimumRole('superAdmin')

                            && PermissionHelpers::requireStatus('active');
                        }
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Message models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new MessageSearch();
        $params =Yii::$app->request->queryParams;

        if(isset($params['MessageSearch']['category'])) {
            $searchModel->category = $params['MessageSearch']['category'];

        };
        if(isset($params['MessageSearch']['message'])) {
            $searchModel->message = $params['MessageSearch']['message'];

        };
        $dataProvider = $searchModel->search($params);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Message model.
     * @param integer $id
     * @param string $language
     * @return mixed
     */
    public function actionView($id, $language)
    {
        return $this->render('view', [
            'model' => $this->findModel($id, $language),
        ]);
    }

    /**
     * Updates an existing Message model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @param string $language
     * @return mixed
     */
    public function actionUpdate($id, $language)
    {
        $model = $this->findModel($id, $language);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['/'.languageSwitcher::getLanguage().'/message/view', 'id' => $model->id, 'language' => $model->language]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Message model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @param string $language
     * @return mixed
     */
    public function actionDelete($id, $language)
    {
        $this->findModel($id, $language)->delete();

        return $this->redirect(['/'.languageSwitcher::getLanguage().'/message/index']);
    }

    /**
     * Finds the Message model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @param string $language
     * @return Message the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id, $language)
    {
        if (($model = Message::findOne(['id' => $id, 'language' => $language])) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/views/message/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use common\components\languageSwitcher;

/* @var $this yii\web\View */
/* @var $model backend\models\Message */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="message-form">

    <?php $form = ActiveForm::begin([
        'action'=>Yii::$app->request->baseUrl.'/'.languageSwitcher::getLanguage().'/message/update?id='
            .$model->id.'&language='.$model->language
    ]); ?>

    <?= $form->field($model, 'language')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'translation')->textarea(['rows' => 6]) ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/message/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use common\components\languageSwitcher;

/* @var $this yii\web\View */
/* @var $model backend\models\MessageSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="message-search">

    <?php $form = ActiveForm::begin([
        'action' => ['/'.languageSwitcher::getLanguage().'/message/index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'language')->dropDownList($model->languageList,
        [
            'prompt'=>'Select language'
        ]) ?>

    <?= $form->field($model, 'translation')->dropDownList($model->translationList,
        [
            'prompt'=>'Select teanslation'
        ]) ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/message/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model backend\models\Message */

$this->title = 'Create Message';
$this->params['breadcrumbs'][] = ['label' => 'Messages', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="message-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/message/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use anmaslov\autocomplete\AutoComplete;
use common\components\languageSwitcher;
use Zelenin\yii\modules\I18n\Module;

/* @var $this yii\web\View */
/* @var $searchModel backend\models\MessageSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Messages';
$this->params['breadcrumbs'][] = $this->title;
echo Module::t('menu', 'about');
?>
<div class="message-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <!--        --><?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            [
                'attribute' => 'category',
                'value' => 'id0.category',
                'filter' => Html::activeDropDownList($searchModel, 'category', $searchModel->categoryList,
                    ['class' => 'form-control', 'prompt' => 'Select Category']),
            ],

            [
                'attribute' => 'message',
                'value' => 'id0.message',
                'filter' => AutoComplete::widget([
                    'model' => $searchModel,
                    'attribute' => 'message',
                    'data' => $searchModel->messageList,
                    'name' => 'MessageSearch[message]',
                    'options'=>[
                        'placeholder'=>'Message'
                    ],
                    'clientOptions' => [
                        'source' => $searchModel->messageList,
                    ]

                ]),
            ],

            [
                'attribute' => 'language',
                'value' => 'language',
                'filter' => Html::activeDropDownList($searchModel, 'language', $searchModel->languageList,
                    ['class' => 'form-control', 'prompt' => 'Select Language']),
            ],
            [
                'attribute' => 'translation',
                'value' => 'translation',
                'filter' => Html::activeDropDownList($searchModel, 'translation', $searchModel->translationList,
                    ['class' => 'form-control', 'prompt' => 'Select Translation']),
            ],

            [
                'class' => 'yii\grid\ActionColumn',
                'template' => '{view} {update} {delete}',
                'buttons' => [
                    'view' => function ($url, $model) {
                        $url = Yii::$app->request->baseUrl . '/' . languageSwitcher::getLanguage() . '/message/view?id='
                            . $model->id . '&language=' . $model->language;
                        return Html::a(
                            '<span class="glyphicon glyphicon-eye-open"></span>',
                            $url);
                    },
                    'update' => function ($url, $model) {
                        $url = Yii::$app->request->baseUrl . '/' . languageSwitcher::getLanguage() . '/message/update?id='
                            . $model->id . '&language=' . $model->language;
                        return Html::a(
                            '<span class="glyphicon glyphicon-edit"></span>',
                            $url);

                    },
                    'delete' => function ($url, $model) {
                        $url = Yii::$app->request->baseUrl . '/' . languageSwitcher::getLanguage() . '/message/delete?id='
                            . $model->id . '&language=' . $model->language;
                        return Html::a('<span class="glyphicon glyphicon-trash"></span>', $url, [
                            'class' => 'classname',
                            'data' => [
                                'method' => 'POST',
                                'confirm' => 'Are you sure you want to delete this item?',
                                'params' => [
                                    'id' => $model->id,
                                    'language' => $model->language
                                ],
                            ]
                        ]);
                    },

                ],

            ],
        ],
    ]); ?>

</div>

backend/views/message/update.php
<?php

use yii\helpers\Html;
use common\components\languageSwitcher;

/* @var $this yii\web\View */
/* @var $model backend\models\Message */

$this->title = 'Update Message: ' . ' ' . $model->messageTitle[$model->id];
$this->params['breadcrumbs'][] = ['label' => 'Messages', 'url' => ['/'.languageSwitcher::getLanguage().'/message/index']];
$this->params['breadcrumbs'][] = ['label' => $model->categorytitle[$model->id], 'url' => [
    '/'.languageSwitcher::getLanguage().'/message/view', 'id' => $model->id, 'language' => $model->language]];
$this->params['breadcrumbs'][] = 'Update';

?>
<div class="message-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/message/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use common\components\languageSwitcher;
use yii\bootstrap\Tabs;
/* @var $this yii\web\View */
/* @var $model backend\models\Message */

$this->title = $model->categoryTitle[$model->id].":".$model->messageTitle[$model->id];
$this->params['breadcrumbs'][] = ['label' => 'Messages', 'url' => ['/'.languageSwitcher::getLanguage().'/message/index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="message-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['/'.languageSwitcher::getLanguage().'/message/update', 'id' => $model->id, 'language' => $model->language], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id, 'language' => $model->language], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'language',
            'translation:ntext',
        ],
    ]) ?>

</div>