backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use backend\models\Genders;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use common\models\LoginForm;
use yii\filters\VerbFilter;
use backend\models\SignupForm;
use common\models\PermissionHelpers;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use backend\models\AddAdminsform;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only'=>['login'],
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['addadmins', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                        'matchCallback' => function ($rule, $action) {
                            return PermissionHelpers::requireMinimumRole('superAdmin')

                            && PermissionHelpers::requireStatus('active');
                        }
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {

        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * render site/index.php file
     * @return string
     */
    public function actionIndex()
    {
            return $this->render('index');
    }

    /**
     * @return string|\yii\web\Response
     */
    public function actionLogin()
    {

        if (!\Yii::$app->user->isGuest) {

            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
                        return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * @return \yii\web\Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * @return string|\yii\web\Response
     */
    public function actionSignup()
    {
        $model = new SignupForm();

        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()) {
                if (Yii::$app->getUser()->login($user)) {
                    return $this->goHome();
                }
            }
        }
        return $this->render('signup', [
            'model' => $model,
        ]);
    }

    /**
     * Requests password reset.
     *
     * @return mixed
     */
    public function actionRequestPasswordReset()
    {
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Check your email for further instructions.');

                return $this->goHome();
            } else {
                Yii::$app->session->setFlash('error', 'Sorry, we are unable to reset password for email provided.');
            }
        }

        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    /**
     * Resets password.
     *
     * @param string $token
     * @return mixed
     * @throws BadRequestHttpException
     */
    public function actionResetPassword($token)
    {
        try {
            $model = new ResetPasswordForm($token);

        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->session->setFlash('success', 'New password was saved.');

            return $this->goHome();
        }

        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }

    /**
     * add new Admins
     *
     * @return string|\yii\web\Response
     */
    public function actionAddadmins()
    {

        $model = new AddAdminsform();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {

                $message = Yii::$app->mailer->compose();
                $message->setFrom('from@domain.com');
                $message->setTo('andranik_muradyan_1990@mail.ru')
                ->setSubject('Message')
                ->setTextBody('your password:'.Yii::$app->request->post()['AddAdminsform']['password_hash'].
                'your email:'.Yii::$app->request->post()['AddAdminsform']['email']
                )
                ->send();
            $model->admins();
            return $this->goHome();
        }
        return $this->render('addadmins',
            [
                'model'=>$model
            ]);

    }
}

backend/views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use backend\assets\AppAsset;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use common\widgets\Alert;
use common\components\languageSwitcher;
use kartik\sidenav\SideNav;
use yii\helpers\Url;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => 'My Company',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-top ',
        ],
    ]);
    if (Yii::$app->user->isGuest) {
        $navItems[] = ['label' => 'Login', 'url' => ['/' . languageSwitcher::getLanguage() . '/site/login']];
    } else {
        $navItems[] = '<li>'
            . Html::beginForm(['/' . languageSwitcher::getLanguage() . '/site/logout'], 'post')

            . Html::submitButton(
                'Logout (' . Yii::$app->user->identity->username . ')',
                ['class' => 'btn btn-link']
            )
            . Html::endForm()
            . '</li>';
    }


    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => $navItems,
    ]);
    ?>
    <?= languageSwitcher::Widget() ?>
    <?php
    NavBar::end();

    ?>
    <div class="container-fluid">
        <div class="col-sm-3">
            <?php
            if (!Yii::$app->user->isGuest) {
                $item='';
                echo SideNav::widget([
                    'type' => SideNav::TYPE_DEFAULT,
                    'items' => [
                        ['label' => 'Home',
                            'icon' => 'home',
                            'url' => Url::to(['/' . languageSwitcher::getLanguage() . '/site/index']),
                            'active' => ($item == 'home')
                        ],
                        ['label' => 'Translation',
                            'icon' => 'tag',
                            'url' => Url::to(['/' . languageSwitcher::getLanguage() . '/message/index']),
                            'active' => ($item == 'message')
                        ],
                        ['label' => 'Languages',
                            'icon' => 'tag',
                            'url' => Url::to(['/' . languageSwitcher::getLanguage() . '/language/index']),
                            'active' => ($item == 'language')
                        ],
                        ['label' => 'Add Admins',
                            'icon' => 'tag',
                            'url' => Url::to(['/' . languageSwitcher::getLanguage() . '/site/addadmins']),
                            'active' => ($item == 'addadmins')
                        ],
                        ['label' => 'Categories',
                            'icon' => 'tag',
                            'active' => ($item == 'categories'),
                            'items'=>[
                                ['label' => 'Categories',
                                    'icon' => 'tag',
                                    'url' => Url::to(['/' . languageSwitcher::getLanguage() . '/categories/index']),
                                    'active' => ($item == 'index')
                                ],
                                ['label' => 'Tree',
                                    'icon' => 'tag',
                                    'url' => Url::to(['/' . languageSwitcher::getLanguage() . '/categories/tree']),
                                    'active' => ($item == 'tree')
                                ],
                            ]
                        ],
                    ],
                ]);
            }
            ?>
        </div>
        <div class="col-sm-9">
            <?= Breadcrumbs::widget([
                'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
            ]) ?>
            <?= Alert::widget() ?>
            <?= $content ?>
            <input class="baseUrl" type="hidden" value="<?= Yii::$app->request->baseUrl.'/'.languageSwitcher::getLanguage()?>">
        </div>
    </div>

</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; My Company <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>